type = "directrequest"
schemaVersion = 1
name = "calcute-token-rating"
externalJobID = "dda63b14-0044-433f-a793-942b3d050069"
forwardingAllowed = false
maxTaskDuration = "0s"
contractAddress = "0x71eDDb50c79bA241B0469bb0Ae08E4f8F7dca45E"
minContractPaymentLinkJuels = "0"
observationSource = """
    decode_log   [type="ethabidecodelog"
                  abi="OracleRequest(bytes32 indexed specId, address requester, bytes32 requestId, uint256 payment, address callbackAddr, bytes4 callbackFunctionId, uint256 cancelExpiration, uint256 dataVersion, bytes data)"
                  data="$(jobRun.logData)"
                  topics="$(jobRun.logTopics)"]
    decode_cbor  [type="cborparse" data="$(decode_log.data)"]
    post        [type="http" method=POST url="https://api.chainstatus.org/chainlink-jobs/calculate-token-rating" requestData="{\\"id\\": $(jobSpec.externalJobID), \\"data\\": { \\"token\\": $(decode_cbor.token), \\"provider\\": $(decode_cbor.provider)}}}" headers="[\\"x-api-key\\", \\"2cfr34VGcZ6R9ep9MnI0\\"]"]
    parse_global_rating        [type=jsonparse path="global_rating" data="$(post)"]
parse_provider_rating        [type=jsonparse path="provider_rating" data="$(post)"]
encode_data  [type="ethabiencode" abi="(bytes32 requestId, uint256 providerRating, uint256 globalRating)" data="{ \\"requestId\\": $(decode_log.requestId), \\"providerRating\\": $(parse_provider_rating), \\"globalRating\\": $(parse_global_rating)}"]
    encode_tx    [type="ethabiencode"
                  abi="fulfillOracleRequest2(bytes32 requestId, uint256 payment, address callbackAddress, bytes4 callbackFunctionId, uint256 expiration, bytes calldata data)"
                  data="{\\"requestId\\": $(decode_log.requestId), \\"payment\\":   $(decode_log.payment), \\"callbackAddress\\": $(decode_log.callbackAddr), \\"callbackFunctionId\\": $(decode_log.callbackFunctionId), \\"expiration\\": $(decode_log.cancelExpiration), \\"data\\": $(encode_data)}"
                  ]
    submit_tx    [type="ethtx" to="0x71eDDb50c79bA241B0469bb0Ae08E4f8F7dca45E" data="$(encode_tx)"]
    decode_log -> decode_cbor -> post -> parse_global_rating -> parse_provider_rating -> encode_data -> encode_tx -> submit_tx
"""
